version: "3"
services:
  uptimebeaver-gateway:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - uptimebeaver-gateway

volumes:
  data:

networks:
  uptimebeaver-gateway:
