apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptimebeaver-gateway
  labels:
    app: uptimebeaver-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptimebeaver-gateway
  template:
    metadata:
      labels:
        app: uptimebeaver-gateway
    spec:
      containers:
        - name: uptimebeaver-gateway
          image: ghcr.io/uptimebeaver/uptimebeaver-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
